# Generated by Django 4.2.4 on 2023-08-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrivateKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("private_key", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="EncryptedMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("topic", models.CharField(max_length=255)),
                ("encrypted_message", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "private_key",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_message",
                        to="encrypting.privatekey",
                    ),
                ),
            ],
        ),
    ]
