# Generated by Django 4.2.4 on 2023-08-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("encrypting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatekey",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="encryptedmessage",
            name="private_key",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encrypted_message",
                to="encrypting.privatekey",
            ),
        ),
    ]
